# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    paths:
      - '**/*src/**/*.java'

jobs:
  datagen:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Cache
        if: always()
        uses: actions/cache@v3.0.11
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: ~/.cache
          # An explicit key for restoring and saving the cache
          key: Gradle-Cache

      - name: Run DataGen
        run: gradle runData -q

      - name: Push
        if: always()
        run: |
          git config --global user.name DataGenCI
          git add .
          git commit -m "datagen" -a
          git push

      - name: Build with Gradle
        if: always()
        run: gradle build -q

      - name: Upload to Release Action
        if: always()
        uses: Shopify/upload-to-release@v1.0.1
        with:
          # Artifact name
          name: kitchenkarrot-demo
          # Path to the file to upload
          path: build/libs
          # secrets.GITHUB_TOKEN
          repo-token: ${{ secrets.GITHUB_TOKEN }}
